//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanBlack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int ID { get; set; }
        public string mastercard { get; set; }
        public Nullable<int> Ammountmastercard { get; set; }
        public string debitcard { get; set; }
        public Nullable<int> Ammountdebitcard { get; set; }
        public Nullable<System.DateTime> date_transation { get; set; }
    }
}
